[packaging] Check for build errors

diff --git a/build b/build
--- a/build
+++ b/build
@@ -49,6 +49,11 @@ build_deb_package() {
     echo "BUILDING .DEB FOR " $1
     cd $1
     ${DEBUILD} -i -us -uc -b
+    if [ $exit != 0 ]
+    then
+        echo "Error building package " $1
+        exit 1
+    fi
     ${DEBUILD} clean
     cd ..
     mv *.deb *.build *.changes ${TARGET_DIR}
@@ -64,6 +69,12 @@ build_submodule_lib() {
     cp -R $1-debian/* $1/debian
     cd $1
     ${DEBUILD} -i -us -uc -b
+    exit=$?
+    if [ $exit != 0 ]
+    then
+        echo "Error building submodule " $1
+        exit 1
+    fi
     ${DEBUILD} clean
     cd ..
     mv *.deb *.build *.changes *.dsc *.tar.gz ${TARGET_DIR}
@@ -101,6 +112,9 @@ build_deb_package filewatcher/scala
 install_in_maven_repo filewatcher/scala/target/*jar-with-dependencies.jar com.nublic filewatcher.scala 0.0.1-SNAPSHOT
 build_deb_package resource/main/src
 #package_and_install resource/java
+# Utilities
+build_deb_package apps/util/gwt
+install_in_maven_repo apps/util/gwt/target/*.jar com.nublic util.gwt 0.0.1-SNAPSHOT
 # Manager App
 build_deb_package apps/app.manager/server
 build_deb_package apps/app.manager/web
@@ -118,4 +132,6 @@ build_deb_package conf/solr
 build_deb_package conf/tomcat6
 build_deb_package conf/nublic
 create_repo
+
+exit 0
 
